runtime: nodejs22
entrypoint: node index.js
env_variables:
  NODE_ENV: "production"
  API_KEY: "AIzaSyCv6YSCCEUlJWiLQgm3YCK2KlQAbrmh9CY"
  OPENROUTE_API_KEY: "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"
  MONGO_URI: "mongodb+srv://pranawrk1_db:Pranaw1234@cluster0.dsca2to.mongodb.net/?appName=Cluster0"
